name: .NET Build and Test

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore MyCalcApp.sln
    - name: Build
      run: dotnet build MyCalcApp.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test MyCalcApp.Tests.csproj --configuration Release --no-build --verbosity detailed